SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`INVOICELINE`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`PLAYLISTTRACK`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`MEDIATYPE`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`GENRE`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`PLAYLIST`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`TRACK`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`INVOICE`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`ALBUM`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`ARTIST`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`CUSTOMER`;

TRUNCATE TABLE `SOLVE-R-US-MYSQL-DB`.`EMPLOYEE`;

SET FOREIGN_KEY_CHECKS = 1;