SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`INVOICELINE`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`PLAYLISTTRACK`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`GENRE`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`PLAYLIST`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`TRACK`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`INVOICE`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`ALBUM`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`MEDIATYPE`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`ARTIST`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`CUSTOMER`;

DROP TABLE `SOLVE-R-US-MYSQL-DB`.`EMPLOYEE`;

SET FOREIGN_KEY_CHECKS = 1;